## One simple or single simple t test :

#### Let we have the titanic dataset and we are assuming that average age of the passengers would be 35,whereas some of us claim that it would be less than 35 . So we are going to do the t-test for this problem statement.

### Answer :

so our null hypothesis (Ho): Average age of the passenger is 35

alternative hypothesis(Ha):Average age is less than 35

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stat

In [2]:
df=sns.load_dataset("titanic")

In [37]:
df["age"].isnull().sum()

177

In [38]:
pop=df["age"].dropna()

In [39]:
pop.isnull().sum()

0

let suppose we have taken 25 sample from the population.

In [40]:
sample=pop.sample(25).values

In [41]:
sample

array([40.  , 42.  , 19.  , 37.  , 30.  , 29.  ,  2.  , 22.  , 26.  ,
       27.  , 22.  , 15.  , 10.  , 51.  , 31.  , 43.  , 19.  ,  4.  ,
       39.  , 32.  ,  0.42, 21.  , 38.  , 35.  , 31.  ])

now we have to test the assumptions

In [42]:
#checking for the normality
from scipy.stats import shapiro

In [43]:
result=shapiro(sample)
p_value=result[1]
if p_value>0.05:
    print("our sample is normally distributed.")
else:
    print("our sample isn't normally distributed.")

our sample is normally distributed.


In [44]:
pop_mean=35

In [45]:
from scipy.stats import ttest_1samp

In [46]:
result=ttest_1samp(sample,pop_mean)
p_value=result[1]/2 # as it is left-tailed test
if p_value>0.05:
    print("Our null hypothesis is true.Average age of the passenger is 35 yr")
else:
    print("we reject our null hypothesis and Average age is less than 35 yr")

we reject our null hypothesis and Average age is less than 35 yr


In [47]:
result

Ttest_1sampResult(statistic=-3.157360962130363, pvalue=0.004257523202690862)

In [49]:
# checking our test with the population dataset 
df["age"].mean()

29.69911764705882

________________________________________________________________________________________________

## Independent 2 sample t-test :

#### now we are claiming that the average age of male and average age for female would be similar.for this we are going to do the t-test.

### Answer

null hypothesis(Ho): average age of  male is similar to the average age of female
    
alternative hypothesis(Ha):average age of  male is not similar to average age of female.there is significant differrence between them.

In [50]:
male_age=df[df["sex"]=='male']["age"]
female_age=df[df["sex"]=='female']["age"]

In [51]:
pop_male_age=male_age.dropna()
pop_female_age=female_age.dropna()

In [52]:
sample_male=pop_male_age.sample(25).values
sample_female=pop_female_age.sample(25).values

In [53]:
sample_male

array([11.  , 74.  , 18.  ,  1.  , 65.  , 45.  , 19.  , 38.  , 22.  ,
       31.  ,  7.  ,  4.  , 44.  , 28.  , 40.5 , 21.  , 36.  , 34.  ,
        0.42, 33.  , 50.  , 70.5 , 70.  , 32.  , 18.  ])

In [54]:
sample_female

array([14., 30.,  7., 18., 16., 40., 49., 38., 43., 38., 45., 29., 45.,
       36.,  4., 35., 41., 29., 51., 22., 19., 17., 30., 54., 21.])

### checking for assumptions

In [55]:
#normality check:

In [56]:
l={"sample_male":sample_male,"sample_female":sample_female}
for i in l:
    result=shapiro(l[i])
    p_value=result[1]
    if p_value>0.05:
        print(f"{i} is normally distributed")
    else:
        print(f"{i} isn't normally distributed")

sample_male is normally distributed
sample_female is normally distributed


In [57]:
# variance test

In [58]:
result=stat.levene(sample_male,sample_female)
if result[1]>0.05:
    print("these two sample columns have equal variance")
else:
    print("variance of these two columns are not equal")

these two sample columns have equal variance


### testing the t-test:

In [62]:
result=stat.ttest_ind(sample_male,sample_female)
if result[1]>0.05:
    print("we can't reject our null hypothesis so average age of male is similar to average age of female ")
else:
    print("average age of male is not similar to average age of female.there is significant differrence between them.")

we can't reject our null hypothesis so average age of male is similar to average age of female 


____________________________________________________________________________________________

## pair two sample t test :

Let's assume that a fitness center is evaluating the effectiveness of a new 8-week weight loss 
program. They enroll 15 participants in the program and measure their weights before and 
after the program. The goal is to test whether the new weight loss program leads to a 
significant reduction in the participants' weight.
Before the program: 
[80, 92, 75, 68, 85, 78, 73, 90, 70, 88, 76, 84, 82, 77, 91]
After the program: 
[78, 93, 81, 67, 88, 76, 74, 91, 69, 88, 77, 81, 80, 79, 88]
Significance level (α) = 0.05

### answer :

so we have data of weight 
Before the program: [80, 92, 75, 68, 85, 78, 73, 90, 70, 88, 76, 84, 82, 77, 91]
and After the program: [78, 93, 81, 67, 88, 76, 74, 91, 69, 88, 77, 81, 80, 79, 88] 

now our null hypothesis(Ho):mean(before)=mean(after)
    
alternative hypothesis(Ha):mean(before)>mean(after)

##### now we need to test our assumptions :

In [64]:
# checking the normality of the different columns of these two columns
column_before=np.array([80, 92, 75, 68, 85, 78, 73, 90, 70, 88, 76, 84, 82, 77, 91])
column_after=np.array([78, 93, 81, 67, 88, 76, 74, 91, 69, 88, 77, 81, 80, 79, 88])

In [65]:
diff_column=column_before-column_after

In [66]:
diff_column

array([ 2, -1, -6,  1, -3,  2, -1, -1,  1,  0, -1,  3,  2, -2,  3])

In [71]:
result=shapiro(diff_column)
p_value=result[1]
if p_value>0.05:
    print("normally distributed")
else:
    print("not normally distreibuted")

normally distributed


now we need to find out the t-statistic.

In [72]:
t_statistic=diff_column.mean()/(diff_column.std()/np.sqrt(15))

In [73]:
t_statistic

-0.10850778933039285

this the right-tailed test.
now we need to find out the p_value with respect to t_statistic

In [78]:
p_value=stat.t.sf(t_statistic,14)
p_value

0.542433629038992

In [77]:
if p_value>0.05:
    print("we can't reject our null hypothesis and mean(before)=mean(after)")
else:
    print("we reject our null hypothesis and (Ha):mean(before)>mean(after)")

we can't reject our null hypothesis and mean(before)=mean(after)


_________________________________________________________________________________________________